### ISSUE TITLE
Possible to adapt to pandas dataframes

### ISSUE THREAD

**Issue by johnbakerh** [donlnz/nonconformist#24]
Hello,

I've been trying to adapt the pipeline based on the example code (ICP_Regression) to my own datasets, however I encounter issues at the following lines. I am working mostly with pandas data-frame and split my data with sci-kit function according to conformal predictions framework. 

#Example Dataframe

    new_host   split  	   sequence	       expression (target)
    FALSE	      train       AQVPYGVS	        0.039267878
    FALSE	      train	    ASVPYGVSI      	0.039267878
    FALSE	      train	    STNLYGSGR	        0.261456561
    FALSE	      test	    NLYGSGLVR	        0.265188519
    FALSE	      test	    SLGPSNLYG	        0.419680588
    FALSE	      test        ATSLGTTNG	         0.145710993

#DataSplit
X_train, X_cal, y_train, y_cal = train_test_split(X_train, y_train, test_size =0.2)

1. icp.fit(X_train, y_train)
2. icp.calibrate(X_cal, y_cal)
3. icp.predict(X_test, significance=0.1))

I managed to make line 1 and 2 work properly by just converting the feature set to a numpy array such as :

y_cal = y_cal.to_numpy()

However line 3 produces an error even when I do this when making the predictions, I've tried multiple ways to adjust my pandas dataframe. 

I was wondering if it would be possible to adapt these functions to be used with pandas dataframe.

Best,

John

**Comment by donlnz** [comment]
It's unlikely that there will be any adaptation specifically to pandas in the near future, as it's quite a lot of work (that makes the code base messier) for relatively little benefit.

If you could provide some extra information about what errors you're getting with pandas dataframes, I might be able to help you pinpoing the problem.
