### ISSUE TITLE
Inductive Conformal Predictor - prediction set and truth

### ISSUE THREAD

**Issue by romass12** [donlnz/nonconformist#25]
I have got output of ICP as: 

	0	1	2
0	c0	c1	Truth
1	1	0	0
2	0	1	1
3	1	1	0
4	1	0	0
5	1	1	0
6	1	1	0
7	1	1	0
8	0	1	1
9	1	1	0
10	1	1	1
11	1	1	1
12	1	0	0
13	1	1	1
14	0	1	1
15	1	1	1
16	1	0	0
17	0	1	0
18	1	1	0
19	1	1	1
20	0	1	1
21	0	1	1
22	1	0	0
23	1	1	1
24	1	1	1
25	0	1	1
26	1	0	1
27	1	0	0
28	1	1	1
29	1	1	0
30	0	1	0
31	1	0	1
32	1	1	1
33	1	0	1
34	1	1	0
35	1	1	1
36	1	0	0
37	1	1	0
38	1	0	0
39	0	1	1
40	1	1	0
41	1	1	0
42	1	1	1
43	1	0	0
44	1	1	0
45	1	1	1
46	1	1	1
47	1	1	0
48	1	1	0
49	0	1	0

Does that mean that wherever c0 and c1(binary classes) are both 1 or 0, then model is uncertain?
@isaksamsten

**Comment by donlnz** [comment]
Yes, that is essentially correct. The model (an ICP classifier) outputs a set of class labels such that the output set has a certain probability (`1 - significance`) of containing the correct class label. If the prediction contains a single class label the model is fairly certain that that particular class label is the correct classification for the test object, whereas if the prediction contains multiple class labels (e.g., both 0 and 1 in the binary case), the model is uncertain in its prediction and effectively gives you the answer that `with confidence 1 - significance, either 0 or 1 is the correct class label`.
